# Generated by Django 5.1.1 on 2024-10-20 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ztoweb', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('about', models.TextField()),
                ('color', models.TextField()),
            ],
        ),
    ]
